### ISSUE TITLE
Add custom listener controls to VirtualServer

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#4094]
Enable the VirtualServer resource to define custom HTTP and HTTPS listener ports

Development branch: https://github.com/nginxinc/kubernetes-ingress/pull/new/vs-custom-listeners

```[tasklist]
### Tasks
- [x] Update GlobalConfigration to add `ssl` field
- [x] Update VirtualServer CRDs to add listener field
- [x] Update VirtualServer to listen on custom ports defined in GlobalConfiguration
- [x] Set VirtualServer envents correctly based on changes to listeners and GlobalConfiguration objects
- [x] Add new example files for custom listeners
- [x] Investigate handling of `forbidden` ports in GlobalConfiguration
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4281
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4196
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4197
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4198
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4234
```
