### ISSUE TITLE
Verify if NIC runs successfully in permission changes as per linked PR

### ISSUE THREAD

**Issue by danielnginx** [nginxinc/kubernetes-ingress#4199]
Verify if NIC runs after the changes from https://github.com/nginxinc/kubernetes-ingress/pull/3962

Deployment and Daemonset

```[tasklist]
### Tasks
- [x] Create an Openshift environment
- [x] Test on Openshift
- [x] Test on GKE
- [x] Test on AKS
- [x] Test on EKS
```

**Comment by jjngx** [comment]
EKS, GKE -> deployment with Nginx+ from prv registries
AKS -> deployment with the official NGINX OSS (Edge) image from DockerHub

**Comment by vepatel** [comment]
Openshift: using testenv
```
~/nginx/kubernetes-ingress/deployments/helm-chart on main ● λ k config get-contexts 
CURRENT   NAME                                                                    CLUSTER                                                      AUTHINFO                                                        NAMESPACE
*         default/api-openshift-e436d78a-testenv-ctrl-nginx-com:6443/kube:admin   api-openshift-e436d78a-testenv-ctrl-nginx-com:6443           kube:admin/api-openshift-e436d78a-testenv-ctrl-nginx-com:6443   default


~/nginx/kubernetes-ingress/deployments/helm-chart on main ● λ helm install test-release --set controller.kind=deployment --set controller.nginxplus=false --set controller.image.pullPolicy=Always .

NAME: test-release
LAST DEPLOYED: Mon Sep 11 16:00:46 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The NGINX Ingress Controller has been installed.

~/nginx/kubernetes-ingress/deployments/helm-chart on main ● λ k get po
NAME                                                     READY   STATUS    RESTARTS   AGE
coffee-77df955494-qtlht                                  1/1     Running   0          3h3m
coffee-77df955494-w6rbq                                  1/1     Running   0          3h3m
tea-6b8fc7844-q5cc9                                      1/1     Running   0          3h3m
test-release-nginx-ingress-controller-6467855784-2nhcd   1/1     Running   0          13s

```

**Comment by vepatel** [comment]
AppProtect in GKE (pending)
