### ISSUE TITLE
Add prometheus servicemonitor support for NGINX Ingress controller

### ISSUE THREAD

**Issue by jasonwilliams14** [nginxinc/kubernetes-ingress#4210]
This enhancement is to support prometheus `servicemonitor` for NGINX Ingress controller helm deployments.

[prometheus-operator Github](https://github.com/prometheus-operator/prometheus-operator)

References:

https://github.com/nginxinc/kubernetes-ingress/issues/889
https://github.com/nginxinc/kubernetes-ingress/issues/3129

Being able to leverage the `servicemonitor` CRD that prometheus provides, allows users to have more flexibility and control when collecting metrics for NGINX Ingress controller.

This request will add support for both `helm` and `manifest` deployments, allowing customer to enable (helm) or apply (manifest) the additional services and servicemonitor that are required.

When using `helm`, if the user opts to enable `servicemonitor` the deployment will generate the appropriate `service` and `servicemonitor` required.
Example manifests (thanks @hostalp)

Additional service required:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-nginx-ingress-servicemonitor
  labels:
    app: nginx-ingress-nginx-ingress-servicemonitor
spec:
  ports:
  - name: prometheus
    protocol: TCP
    port: 9113
    targetPort: 9113
  selector:
    app: nginx-ingress-nginx-ingress
```
Servicemonitor definition:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-nginx-ingress-servicemonitor
  labels:
    app: nginx-ingress-nginx-ingress-servicemonitor
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: nginx-ingress-nginx-ingress-servicemonitor
  endpoints:
  - port: prometheus
```

The user will have to have ensure they have prometheus installed and running correctly in there cluster in order for `servicemonitor` to work correctly.

```[tasklist]
### Tasks
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4329
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4328
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4330
```

**Comment by AaronShiels** [comment]
Looks like exactly what is needed to finally get out-of-the-box Prometheus metrics!

**Comment by jasonwilliams14** [comment]
Attached drawing to show connections for `service`, `servicemonitor` and `prometheus`.


![nic-servicemonitor](https://github.com/nginxinc/kubernetes-ingress/assets/20735496/11570621-84bd-418d-b086-dc739cbf1b76)
