### ISSUE TITLE
Add documentation for custom listeners

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#4281]
This issue relates to changes from this PR: https://github.com/nginxinc/kubernetes-ingress/pull/4271

The tasks listed below aim to update the existing documentation for both VirtualServer and GlobalConfiguration, as well as include a new "How to" document for deploying a VirtualServer with custom listeners.

This will include updates to add descriptions for the new `listener` field for VirtualServer and the new `ssl` field for GlobalConfiguration.

For VirtualServer, this will affect the [VirtualServer Specification](https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#virtualserver-specification) section, as well as adding a new section with details for the `http` and `https` listener fields.

For GlobalConfiguration, this will affect the [GlobalConfiguration Specification](https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#virtualserver-specification) section, as well as updating the `protocol` section to mention support for `HTTP` and add details for the new `ssl` field.

```[tasklist]
### Tasks
- [x] Updating existing documentation for VirtualServer
- [x] Update existing documentation for GlobalConfiguration
- [x] Add new "How to" tutorial document on deploying a VirtualServer with custom listeners
```
