### ISSUE TITLE
Helm Chart and deployment manifests

### ISSUE THREAD

**Issue by lucacome** [nginxinc/kubernetes-ingress#4287]
### Discussed in https://github.com/nginxinc/kubernetes-ingress/discussions/4195

<div type='discussions-op-text'>

<sup>Originally posted by **lucacome** August  8, 2023</sup>
I'd like to get early feedback about a "refactor" of the Helm chart directory and the generation of deployment manifests based on use cases.

The first part is about moving the helm chart to the root of the project and inside the `nginx-ingress` folder to follow Helm's best practices. This means that the new structure would be `charts/nginx-ingress` instead of `deployments/helm-chart/`.
Will this cause any problems? Maybe with existing automation? Would release notes be enough to cover this?
I would expect most people to pull the chart locally if they want to modify the `values.yaml` file, with something like `helm pull oci://ghcr.io/nginxinc/charts/nginx-ingress --untar --version 0.18.0`, but feedback is appreciated.

The second part is to create deployments for different use cases, generating them from the Helm Chart to have a single source of truth, something like:
```
deploy/
├── README.md
├── app-protect-dos
│   └── deploy.yaml
├── app-protect-waf
│   └── deploy.yaml
├── aws-nlb
│   └── deploy.yaml
...
└── read-only-fs
    └── deploy.yaml
```
These manifest files will have everything that's needed for the deployment in a single file, `Service`, `Service Account`, `Namespace`, `Deployment`, etc.
Would this be helpful? What use cases should we consider adding? Should we also include CRDs in there?

Any feedback would be greatly appreciated 🙏 
</div>

```[tasklist]
### Tasks
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4396
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4434
- [ ] https://github.com/nginxinc/kubernetes-ingress/pull/4278
```

**Comment by danielnginx** [comment]
@lucacome There is a concern that this could be customer impacting, could we break it into smaller changes? 

Do we need a major release to support these changes? Do we need a major version in the helm chart? 

Could we split this issue into 3 issues?

- Moves the Helm Chart to charts/nginx-ingress.

- Uses Helm Charts in examples/helm-chart to template single file manifests in deploy/.

- Adds kustomize to create a single CRDs file and single files CRDs for NAP WAF and NAP DoS.

**Comment by vepatel** [comment]
As per @danielnginx's comment, separate issues are required

**Comment by lucacome** [comment]
sure go ahead and create them @danielnginx @vepatel
