### ISSUE TITLE
Epic - Weight changes for backends should not trigger a reload

### ISSUE THREAD

**Issue by brianehlert** [nginxinc/kubernetes-ingress#4404]
### Discussed in https://github.com/nginxinc/kubernetes-ingress/discussions/3741

<div type='discussions-op-text'>

<sup>Originally posted by **brianehlert** April 10, 2023</sup>
When only the weight is changed for upstreams, such as performing a blue/green or canary - NGINX Plus should not be reloaded.
This is possible through the N+ API just like dynamic upstream configuration.
This idea is described here:
https://www.nginx.com/blog/dynamic-a-b-testing-with-nginx-plus/#Using-the-Key-Value-Store-with-Split-Clients
NGINX Ingress Controller already uses Split Clients to implement the weight feature.

- Support weights of 0 - 100 (1 - 99 is constraining)
- make weight changes without reloading
- Plus exclusive feature (changes without reload)
- NGINX OSS will still reload on weight change

This work should primarily be about using the NGINX Plus API to apply the weight changes when NGINX Plus is present.
If the deployment is using NGINX OSS then a soft reload should still be required.

This work can be split when delivered</div>
```[tasklist]
### Tasks
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4509
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4510
- [x] Investigate use of dynamic split clients module
- [x] Investigate use of NJS modules to add custom JS function for split clients
```

Aha! Link: https://nginx.aha.io/epics/NIC-E-126
