### ISSUE TITLE
`backup` server in upstream for VirtualServer and TransportServer not removed when the backup services is deleted

### ISSUE THREAD

**Issue by jjngx** [nginxinc/kubernetes-ingress#4774]
Updates required:

- Deleting BackupService associated with the Upstream should remove backup entry from NGINX config file (Upstream)
- Deleting ConfigMap entry - `resolver-addresses` should trigger Warning

Updates required for tests:
- update `test_transport_server_backup_service.py` to validate connection to external service when backend application is unavailable
- Add unit tests to validate fields
- Add python tests to make sure if removing backup service sends VS/TS into warning

Investigation notes:
When debugging the issue, we found that both VS and TS resources we not checking if they had a reference to the backup service. Adding a line in reference_checker.go for both VS and TS resources looks to have resolved the issue.

Service reference check for VirtualServer: https://github.com/nginxinc/kubernetes-ingress/blob/main/internal/k8s/reference_checkers.go#L141

Service reference check for TransportServer: https://github.com/nginxinc/kubernetes-ingress/blob/main/internal/k8s/reference_checkers.go#L175

```[tasklist]
### Tasks
- [x] Investigate why the config file is not updated
- [x] The `backup` directive in an upstream should be removed when the backup service is deleted for VirtualServer
- [x] The `backup` directive in an upstream should be removed when the backup service is deleted for TransportServer
```

**Comment by brianehlert** [comment]
I am fine with not adding additional resource watchers at this point in time.  The configuration will eventually update and I think that is fine to support the upstream backup capability.

Such as trying to be smart if the ExternalnameService changes or is deleted.  We will address that with additional work.
That is captured here: https://github.com/nginxinc/kubernetes-ingress/discussions/4816
