### ISSUE TITLE
Release NGINX Ingress Controller

### ISSUE THREAD

**Issue by danielnginx** [nginxinc/kubernetes-ingress#4781]
Release NGINX Ingress Controller 3.4.0
```[tasklist]
### Tasks
- [x] Create the release-3.4 branch
- [x] Docs release note & Changelog
- [x] Upgrade testing
- [x] AWS Release
- [x] Rancher release verification
- [x] GKE/GCP Release
- [x] Release Operator
```
