### ISSUE TITLE
Telemetry Job

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#4863]
As a maintainer of NIC
I want a telemetry job that collects data every 24 hours
So that I can eventually send collected telemetry data to a centralized collector.

Acceptance Criteria
- The telemetry job outputs some set of dummy data every time data would be collected to the debug log.
- The telemetry job attempts to collect data every 24 hours, starting at initial deployment of NIC.
- The time period at which data is collected can be configured by a developer for testing.
- Only the leader pod runs the job
```[tasklist]
### Tasks
- [x] The telemetry job outputs some set of dummy data every time data would be collected to the debug log.
- [x] The telemetry job attempts to collect data every 24 hours, starting at initial deployment of NIC
- [x] The time period at which data is collected can be configured by a developer for testing.
- [x] Only the leader pod runs the job
- [x] Allow users to opt-out of exporting telemetry by means of a cli flag
```
