### ISSUE TITLE
Epic - Adoption Telemetry

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#4877]
As a maintainer of NIC, I would like to provide the product with a means to collect Product Telemetry so that I can better understand how our users configure our product

**Data Collection**
Some data points that NIC is interested in collecting has been implemented by the [nginx-cluster-connector](https://github.com/nginxinc/nginx-cluster-connector)

Details can be found in the [data-design](https://github.com/nginxinc/nginx-cluster-connector/blob/main/data-design.md) for the cluster connector

```[tasklist]
### Tasks
- [x] Update all `int` data types to `int64`
- [ ] Confirm data is sent to XCDF devendpoint
- [ ] Document process for changes/updates to schema
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4863
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4902
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4903
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5123
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4883
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5136
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5143
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5151
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4882
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5144
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5135
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5137
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5138
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5139
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5140
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5141
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5142
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4884
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/4898
- [x] Define Schema for NIC
- [ ] Enable Telemetry Job to collect version of App protect
- [x] Add Telemetry opt-out option in Helm
- [ ] Deploy CronJob to send telemetry data to the Dev endpoint every 24h using the `edge` image
```

**Comment by shaun-nx** [comment]
re-opening. Was closed after I linked an issue to it
