### ISSUE TITLE
Release NGINX Ingress Controller 3.4.3

### ISSUE THREAD

**Issue by danielnginx** [nginxinc/kubernetes-ingress#4998]
Release NGINX Ingress Controller 3.4.3

Cherry Pick:

- [x] https://github.com/nginxinc/kubernetes-ingress/issues/4727
- [x] https://github.com/nginxinc/kubernetes-ingress/issues/4952
- [x] https://github.com/nginxinc/kubernetes-ingress/pull/5041
- [x] https://github.com/nginxinc/kubernetes-ingress/pull/4832
- [x] https://github.com/nginxinc/kubernetes-ingress/pull/5071

NGINX Version update

```[tasklist]
### Tasks
- [ ] Docs release note & Changelog
- [ ] AWS Release
- [ ] Rancher release verification
- [ ] GCP Release
- [ ] Release Operator
```
