### ISSUE TITLE
Document process for changes/updates to schema

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#5220]
```[tasklist]
### Tasks
- [x] Create README on how to generate update attributes functions and generate AVRO schema
- [x] Add `make` target for generating both attributes and AVRO schema
- [x] Ensure `make` target runs `gofmt -w .` to ensure gnerated code is formatted
```
