### ISSUE TITLE
Upgrade testing - Release 3.5

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#5281]
UAC:
- Perform upgrade testing for release 3.5

Stretch-goals:
- Automate `Prerequisites` list
- Example/test applications to deploy

Test images in GCR:

3.4
- WAF+DOS: `gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/nginx-ic-dos-nap/nginx-plus-ingress:release-3.4`
- NGINX Plus: `gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/nginx-ic/nginx-plus-ingress:release-3.4`
- NGINX OSS: `gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/nginx-ic/nginx-ingress:release-3.4`

3.5
- WAF+DOS: `gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/nginx-ic-dos-nap/nginx-plus-ingress:release-3.5`
- NGINX Plus: `gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/nginx-ic/nginx-plus-ingress:release-3.5`
- NGINX OSS: `gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/nginx-ic/nginx-ingress:release-3.5`

```[tasklist]
### Prerequisites
- [x] A GKE/AKS/EKS cluster
- [x] Checkout current release branch and installation NIC from that release (Helm is preferred)
- [x] An Ingress resource example with application
- [x] A VS resource example with application
- [x] A VS-VSR-Policy resource example with application
- [x] A simple TS resource example with application
- [x] A tls-passthrough TS resource example with application
- [x] AppProtect WAF and DoS examples and apps depending on features added/removed in coming release
```

```[tasklist]
### AppProtect WAF+DOS upgrade
- [x] Install CRDs from release-3.4 branch
- [x] Helm install of release-3.4
- [x] Confirm applications operate on release-3.4 branch
- [x] Install CRDs from release-3.5 branch
- [x] Helm upgrade on release-3.5 branch
- [x] Confirm applications operate on release-3.5 branch
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/pull/5259
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/5145
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/5050
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/5191
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4877
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4509
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4942 (Do an upgrade from 3.4 to 3.5 with RFS enabled)
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4603
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4665
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/pull/5053
```

```[tasklist]
### NGINX Plus Upgrade
- [x] Install CRDs from release-3.4 branch
- [x] Helm install of release-3.4
- [x] Confirm applications operate on release-3.4 branch
- [x] Install CRDs from release-3.5 branch
- [x] Helm upgrade on release-3.5 branch
- [x] Confirm applications operate on release-3.5 branch
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/5050
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/5191
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4877
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4942 (Do an upgrade from 3.4 to 3.5 with RFS enabled)
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4509
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4603
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4665
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/pull/5053
```

```[tasklist]
### NGINX OSS Upgrade
- [x] Install CRDs from release-3.4 branch
- [x] Helm install of release-3.4
- [x] Confirm applications operate on release-3.4 branch
- [x] Install CRDs from release-3.5 branch
- [x] Helm upgrade on release-3.5 branch
- [x] Confirm applications operate on release-3.5 branch
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/5050
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/5191
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4603
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4509 (should not work for OSS)
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4665
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4877
- [x] Validate https://github.com/nginxinc/kubernetes-ingress/issues/4942 (Do an upgrade from 3.4 to 3.5 with RFS enabled)
```
