### ISSUE TITLE
Release NGINX Ingress Controller 3.5.0

### ISSUE THREAD

**Issue by danielnginx** [nginxinc/kubernetes-ingress#5289]
Release NGINX Ingress Controller 3.5.0
```[tasklist]
### Tasks
- [x] Create the release-3.5 branch
- [x] Docs release note & Changelog
- [x] Upgrade testing
- [x] AWS Release
- [x] Rancher release verification
- [x] GKE/GCP Release
- [x] Release Operator
```
