### ISSUE TITLE
Epic - Support NAP WAF v5

### ISSUE THREAD

**Issue by brianehlert** [nginxinc/kubernetes-ingress#5290]
NGINX AppProtect WAF released a new architecture with major release 5.
This new architecture brings new flexibility through management of installables, campaigns, signatures, policy, etc. and also capabilities.
https://docs.nginx.com/nginx-app-protect-waf/v5/

The NIC team needs to investigate the new architecture and determine how to best make it available to NIC customers who choose to run WAF at the edge of their Kubernetes clusters.

- How to implement WAF v5 as a greenfield for customers new to WAF + NIC (all components, it must be a complete solution.  WAF container, extension, controller, Policy/annotation updates, workflow, etc.)
- Suggestions around how to maintain support for existing WAF v4 while also supporting WAF v5 to form the basis for an internal discussion
- Align with the WAF team to ensure we have a viable path moving forward, including how we support migrating customers moving from v4 to v5
- Align with WAF management plans

Related project of note: https://github.com/fabriziofiorucci/NAP-Compiler-REST-API

Deployment guide/steps:
https://docs.nginx.com/nginx-app-protect-waf/v5/admin-guide/deploy-on-kubernetes/#manifest-deployment

```[tasklist]
### Tasks
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5296
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5430
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5483
```

Aha! Link: https://nginx.aha.io/epics/NIC-E-119
