### ISSUE TITLE
Design - Support NAP WAF v5

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#5296]
### Documentation and references

How to deploy build and deploy WAF v5 in kubernetes.
https://docs.nginx.com/nginx-app-protect-waf/v5/admin-guide/deploy-on-kubernetes/

### Releases
[NGINX App Protect WAF Release 4.8.1](https://docs.nginx.com/nginx-app-protect-waf/v4/releases/release-notes-4.8.1/) 
[NGINX App Protect WAF Release 4.9](https://docs.nginx.com/nginx-app-protect-waf/v4/releases/release-notes-4.9/) 
[NGINX App Protect WAF Release 5.1](https://docs.nginx.com/nginx-app-protect-waf/v5/releases/release-notes-5.1/)

```[tasklist]
### Tasks
- [x] Determine if WAFv5 will be loaded as a Sidecar
- [x] Identify areas of change in NIC
- [ ] Deploy WAF v5 on NGINX alone (excluding NIC)
- [x] Deploy NIC with WAF v4 with JSON policy
- [x] Deploy NIC with WAF v4 with bundle policy
```

```[tasklist]
### Deployment test
- [x] NIC with WAF v4.9 for Debian
- [x] NIC with WAF v4.9 for Alpine
- [x] NIC with WAF v4.9 for UBI (Redhat)
- [ ] NIC with WAF v5 for Debian
- [ ] NIC with WAF v5 for Alpine
- [ ] NIC with WAF v5 for UBI (Redhat)
```

```[tasklist]
### Tasks
- [ ] Update [k8s-common](https://github.com/nginxinc/k8s-common/tree/main/files) repo to add repos for WAF v5
```
