### ISSUE TITLE
Support APIKey authentication - Implementation

### ISSUE THREAD

**Issue by danielnginx** [nginxinc/kubernetes-ingress#5484]
- Create a Policy for API Key Auth
	- The policy should work for virtualserver and virtualserver routes
	- The policy should be implemented in NJS
	- The APIKey should be hashed
	- The policy should support multiple apikeys
	- Should support multiple headers/queries
```[tasklist]
### Tasks
- [x] Unit tests
- [x] Python Tests
- [x] Example folder in repo
- [x] clean up logs
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5761
```
