### ISSUE TITLE
Release NGINX Ingress Controller 3.5.2

### ISSUE THREAD

**Issue by danielnginx** [nginxinc/kubernetes-ingress#5551]
Add support to NGINX PLUS R32

Notes: make sure that we have the latest base images

```[tasklist]
### Tasks
- [x] QE sign off - ensure that we are shipping without bugs and we have the latest base OS images
- [ ] Security sign off - ensure that we are not shipping any fixable CVE's and if we have CVE's they are documented
- [ ] https://github.com/nginxinc/kubernetes-ingress/issues/5555
- [x] Docs release note & Changelog
- [x] AWS Release
- [x] Rancher release verification
- [x] GCP Release
- [x] Release Operator
- [x] Update NGINX OSS
- [x] Unpin version WAF version 4
- [x] Document the WAF changes
```

**Comment by oseoin** [comment]
Base OS images confirmed [up to date](https://github.com/nginxinc/kubernetes-ingress/actions/runs/9282759502/job/25541472875): 

```
The provided SHA256 hash is the latest for opentracing/nginx-opentracing:nginx-1.25.4
The provided SHA256 hash is the latest for opentracing/nginx-opentracing:nginx-1.25.4-alpine
The provided SHA256 hash is the latest for ghcr.io/nginxinc/alpine-fips:0.1.0-alpine3.17
The provided SHA256 hash is the latest for ghcr.io/nginxinc/alpine-fips:0.1.2-alpine3.[19](https://github.com/nginxinc/kubernetes-ingress/actions/runs/9282759502/job/25541472875#step:3:20)
The provided SHA256 hash is the latest for nginx:1.25.4-alpine
The provided SHA256 hash is the latest for nginx:1.25.4
The provided SHA256 hash is the latest for nginxcontrib/nginx:1.25.4-ubi
The provided SHA256 hash is the latest for alpine:3.19
The provided SHA256 hash is the latest for alpine:3.17
The provided SHA256 hash is the latest for debian:12-slim
The provided SHA256 hash is the latest for debian:11-slim
The provided SHA256 hash is the latest for redhat/ubi9-minimal
The provided SHA256 hash is the latest for redhat/ubi9
The provided SHA256 hash is the latest for redhat/ubi8
> A newer version of golang:1.22-alpine is available:
> - golang:1.22-alpine@sha256:b8ded51bad03238f67994d0a6b88680609b392db04312f60c23358cc878d4902
> + golang:1.22-alpine@sha256:4[21](https://github.com/nginxinc/kubernetes-ingress/actions/runs/9282759502/job/25541472875#step:3:22)bc7f4b90d042c56282bb894451108f8ab886687e1b73abaefad31ab10a14d
> updating ./build/Dockerfile
> A newer version of golang:1.[22](https://github.com/nginxinc/kubernetes-ingress/actions/runs/9282759502/job/25541472875#step:3:23)-alpine is available:
> - golang:1.22-alpine@sha256:b8ded51bad03[23](https://github.com/nginxinc/kubernetes-ingress/actions/runs/9282759502/job/25541472875#step:3:24)8f67994d0a6b88680609b392db04312f60c23358cc878d4902
> + golang:1.22-alpine@sha256:421bc7f4b90d042c56282bb894451108f8ab886687e1b73abaefad31ab10a14d
> updating ./build/Dockerfile
The provided SHA[25](https://github.com/nginxinc/kubernetes-ingress/actions/runs/9282759502/job/25541472875#step:3:26)6 hash is the latest for kindest/node:v1.29.2
The provided SHA256 hash is the latest for python:3.12
```
`golang:1.22-alpine` is not shipped

**Comment by oseoin** [comment]
Pre-release final check of base OS images: https://github.com/nginxinc/kubernetes-ingress/actions/runs/9318884521/job/25652142377
`golang:1.22-alpine` is only used for local development so should not impact release
