### ISSUE TITLE
Add NAP-WAF and NAP-WAF+DOS support for debian 12 images

### ISSUE THREAD

**Issue by vepatel** [nginxinc/kubernetes-ingress#5588]
Add NAP-WAF support for Debian 12 images for both v4 and v5
Add NAP-WAF+DOS support for Debian 12 images for both v4 and v5

```[tasklist]
### Tasks
- [ ] Remove duplicated code related to Debian 12
- [ ] Use debian-plus as base
- [ ] Update tech spec doc regarding upgrade to Debian 12 (https://docs.nginx.com/nginx-ingress-controller/technical-specifications/#images-with-nginx-plus)
```

**Comment by shaun-nx** [comment]
All of the changes in [this](https://github.com/nginxinc/kubernetes-ingress/pull/5698/commits/c9a0771bf7f5a07a99babe0ce8d647e89b609be7) commit should be the same changes that need to happen for the `debian-plus-nap` build stage.
