### ISSUE TITLE
Integrate NAP WAF v5

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#5646]
As an engineer of the NGINX Ingress Controller, I would like to integrate NGINX AppProtect v5 so that we can continue to deliver the latest security features to our users.

This issue is a continuation of the POC effort to integrate NGINX AppProtect v5.
Details of that issue are captured here: https://github.com/nginxinc/kubernetes-ingress/issues/5483
Epic here: https://github.com/nginxinc/kubernetes-ingress/issues/5290

Relates issues:
[Add NAP-WAF only support for debian 12 images](https://github.com/nginxinc/kubernetes-ingress/issues/5588)

```[tasklist]
### UACs
- [x] Update Dockerfile to add build stages for NAP v5
- [x] Update codebase to work with both NAP v4 and NAP v5
- [x] Add Helm configuration options for NAP v5
- [x] Add UBI 8 and UBI 9 repo files to k8s-common repo
- [x] Update Debian build stages to use Debian 12
```

```[tasklist]
### Tasks
- [ ] Update [AppProtect Deployment](https://docs.nginx.com/nginx-ingress-controller/installation/integrations/app-protect-waf/installation/#deploy-ingress-controller) docs to change bundle path
- [x] Update Helm to allow PVC to be specified
- [ ] Write basic Python test(s) with bundles
- [ ] Update pipeline - build bundle(s) for testing
- [ ] Integration tests for NIC + WAF v5
- [ ] New docs on how to configure and deploy NIC with WAF v5
- [ ] Docker Scout tests + report
```
