### ISSUE TITLE
Release NGINX Ingress Controller 3.6.0

### ISSUE THREAD

**Issue by danielnginx** [nginxinc/kubernetes-ingress#5729]
Release NGINX Ingress Controller 3.6.0

```[tasklist]
### Tasks
- [x] Create the release branch
- [x] Reenable cherry pick
- [x] Upgrade testing
- [x] QE sign off - ensure that we are shipping without bugs and we have the latest base OS images
- [x] Security sign off - ensure that we are not shipping any fixable CVE's and if we have CVE's they are documented
- [x] Docs release note & Changelog
- [x] Release Operator
```
