### ISSUE TITLE
Release NGINX Ingress Controller 3.6.1

### ISSUE THREAD

**Issue by danielnginx** [nginxinc/kubernetes-ingress#5942]
Release NGINX Ingress Controller 3.6.1

```[tasklist]
### Tasks
- [x] Create the release branch
- [ ] QE sign off - ensure that we are shipping without bugs and we have the latest base OS images
- [ ] Security sign off - ensure that we are not shipping any fixable CVE's and if we have CVE's they are documented
- [ ] Docs release note & Changelog
- [x] Release Operator
```
