### ISSUE TITLE
Release NGINX Ingress Controller 3.6.2

### ISSUE THREAD

**Issue by danielnginx** [nginxinc/kubernetes-ingress#6138]
```[tasklist]
### Tasks
- [x] Create the release branch
- [x] QE sign off - ensure that we are shipping without bugs and we have the latest base OS images
- [x] Security sign-off - ensure that we are not shipping any fixable CVE's and if we have CVE's they are documented
- [x] Docs release notes & Changelog
- [x] Release Operator
```
