### ISSUE TITLE
Merge AppProtect version updates into release-3.7 branch

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#6343]
Update WAF v5 component versions in main and cp them to release branch
```[tasklist]
### Tasks
- [ ] Update `main` branch with latest version of all WAF components after release on `Sept 25th`
- [ ] Update `release-3.7` branch with latest version of all WAF components after release on `Sept 25th`
- [ ] Update version of WAF components in documentation
- [ ] Update version of WAF components in tests
- [ ] Update version of WAF components in workflow
```
