### ISSUE TITLE
POC - Routing based on HostHeader without tls-passthrough

### ISSUE THREAD

**Issue by shaun-nx** [nginxinc/kubernetes-ingress#6438]
```[tasklist]
### Tasks
- [x] Diagram detailing deployment scenarios (mind map)
- [x] Detail security considerations
- [x] Create design document
```
